name: trash_system
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  cupertino_icons: ^1.0.6
  mysql1: 0.20.0
  logger: ^2.3.0
  crypto: ^3.0.1
  sqflite: any
  path: any
  http: ^0.13.3
  bcrypt: 1.1.3
  encrypt: ^5.0.1
  flutter_bcrypt: 1.0.8
  sqflite_common_ffi: any
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/trash_icon.png
    - assets/profile.png
    - assets/Waste_Map_thumb_1200x630.jpg
    - assets/wallpaper.jpg
    - assets/logo.png
